# 1. Convert tuple to list, set and dictionary

tuple $\rightarrow$ list

In [1]:
T_1 = (1, 2, 2, 3.5, 4, 4, 19.38, 'A', 'B', 'seinfeld', 'B')
print('The content of T_1 are :',T_1)
print('the type of T_1 :', type(T_1))

L_1 = list(T_1)
print('\nThe content of L_1 are :',L_1)
print('the type of L_1 :', type(L_1))


The content of T_1 are : (1, 2, 2, 3.5, 4, 4, 19.38, 'A', 'B', 'seinfeld', 'B')
the type of T_1 : <class 'tuple'>

The content of L_1 are : [1, 2, 2, 3.5, 4, 4, 19.38, 'A', 'B', 'seinfeld', 'B']
the type of L_1 : <class 'list'>


tuple $\rightarrow$ set

In [2]:
S_1 = set(T_1)
print('The content of S_1 are :',S_1)
print('The type of S_1 :',type(S_1))


The content of S_1 are : {1, 2, 3.5, 4, 'B', 'seinfeld', 19.38, 'A'}
The type of S_1 : <class 'set'>


tuple $\rightarrow$ dictionary

The tuple S_1 defined cannot be converted to a dictionary in the aove form. However a tuple of tuples can be converted to a dictionary. This is shown in below. 

In [3]:
T_2 = (('Joydeep', ('breakfast',150)), ('Subhayan', ('lunch',200)), ('Mrinal', ('breakfast', 200)), ('Soumitra', ('Dinner',500)))
print('The type of T_2 is ',type(T_2),'\n')
D_1 = dict(T_2)
print('The type of S_2 is ',type(D_1))
print('The content of S_2 is\n',D_1)

The type of T_2 is  <class 'tuple'> 

The type of S_2 is  <class 'dict'>
The content of S_2 is
 {'Joydeep': ('breakfast', 150), 'Subhayan': ('lunch', 200), 'Mrinal': ('breakfast', 200), 'Soumitra': ('Dinner', 500)}


# 2. Convert list to tuple, set and dictionary

list $\rightarrow$ tuple

In [4]:
L_2 = ['Meluha', 'cycle', 'wallet', 50, '4 litres', 'lofi hiphop', 100, 3.8, 5, 5]
print('The type of L_2 is ', type(L_2))
print('The content of L_2 is\n', L_2, '\n')

T_3 = tuple(L_2)
print('The type of T_3 is', type(T_3))
print('The content of T_3 is', T_3)

The type of L_2 is  <class 'list'>
The content of L_2 is
 ['Meluha', 'cycle', 'wallet', 50, '4 litres', 'lofi hiphop', 100, 3.8, 5, 5] 

The type of T_3 is <class 'tuple'>
The content of T_3 is ('Meluha', 'cycle', 'wallet', 50, '4 litres', 'lofi hiphop', 100, 3.8, 5, 5)


list $\rightarrow$ set

In [5]:
S_2 = set(L_2)
print('The type of S_2 is',type(S_2))
print('The content of S_2 is',S_2)

The type of S_2 is <class 'set'>
The content of S_2 is {3.8, 100, 5, 'wallet', '4 litres', 'lofi hiphop', 50, 'cycle', 'Meluha'}


list $\rightarrow$ dictionary

The list L_2 is the above cannot be converted to a dictionary but similar to the case of the tuple, a list of lists can be converted to a dictionary.   

In [6]:
L_3 = [['Joydeep', ['breakfast',150]], ['Subhayan', ['lunch',200]], ['Mrinal', ['breakfast', 200]], ['Soumitra', ['Dinner',500]]]
print('The type of L_3 is',type(L_3),'\n')

D_2 = dict(L_3)
print('The type of D_2 is',type(D_2))
print('The content of D_2 is\n',D_2)

The type of L_3 is <class 'list'> 

The type of D_2 is <class 'dict'>
The content of D_2 is
 {'Joydeep': ['breakfast', 150], 'Subhayan': ['lunch', 200], 'Mrinal': ['breakfast', 200], 'Soumitra': ['Dinner', 500]}


# 3. Convert a set to tuple

set $\rightarrow$ tuple

In [7]:
S_2 = {'Meluha', 'cycle', 'wallet', 50, '4 litres', 'lofi hiphop', 100, 3.8, 5, 5}
print('The type of S_2 is',type(S_2))
print('The content of S_2 is',S_2,'\n')

T_4 = tuple(S_2)
print('The type of T_4 is',type(T_4))
print('The content of T_4 is',T_4)

The type of S_2 is <class 'set'>
The content of S_2 is {3.8, 100, 5, 'wallet', '4 litres', 'lofi hiphop', 50, 'cycle', 'Meluha'} 

The type of T_4 is <class 'tuple'>
The content of T_4 is (3.8, 100, 5, 'wallet', '4 litres', 'lofi hiphop', 50, 'cycle', 'Meluha')


set $\rightarrow$ list

In [8]:
L_3 = list(S_2)
print('The type of L_3 is',type(L_3))
print('The content of L_3 is',L_3)

The type of L_3 is <class 'list'>
The content of L_3 is [3.8, 100, 5, 'wallet', '4 litres', 'lofi hiphop', 50, 'cycle', 'Meluha']


set $\rightarrow$ dictionary 

Similar to the cases before a set of sets can be converted to a dictionary 

In [9]:
S_3 = {('Joydeep',150), ('Subhayan', 200), ('Mrinal', 200), ('Soumitra',500)}
D_3 = dict(S_3)
print(D_3)

{'Subhayan': 200, 'Soumitra': 500, 'Mrinal': 200, 'Joydeep': 150}


# 4. Convert a Dictionary to a tuple

Dictionary $\rightarrow$ tuple

In [57]:
D_4 = {'Joydeep':(150, 200), 'Subhayan':200, 'Mrinal':200, 'Soumitra':500}
print('The type of D_4',type(D_4))
print('The content of D4 is',D_4,'\n')

T_5_1 = tuple(D_4.keys())
T_5_2 = tuple(D_4.values())
T_5 = T_5_1 + T_5_2
print('The content of T_5 is',T_5)

The type of D_4 <class 'dict'>
The content of D4 is {'Joydeep': (150, 200), 'Subhayan': 200, 'Mrinal': 200, 'Soumitra': 500} 

The content of T_5 is ('Joydeep', 'Subhayan', 'Mrinal', 'Soumitra', (150, 200), 200, 200, 500)


Dictionary $\rightarrow$ list

In [58]:
L_5_1 = list(D_4.keys())
L_5_2 = list(D_4.values())
L_5 = L_5_1 + L_5_2
print('The content of L_5 is',L_5)

The content of L_5 is ['Joydeep', 'Subhayan', 'Mrinal', 'Soumitra', (150, 200), 200, 200, 500]


Dictionary $\rightarrow$ list

In [60]:
S_5_1 = set(D_4.keys())
S_5_2 = set(D_4.values())
S_5 = S_5_1.union(S_5_2)
print('The content of S_5 is',S_5)

The content of S_5 is {'Subhayan', 'Mrinal', 500, (150, 200), 200, 'Soumitra', 'Joydeep'}


# 5. Create a list and perform pop, append, update, remove, delete, add element and sort operation


Pop operation

In [198]:
L1 = ['Meluha', 'cycle', 'wallet', 50, '4 litres', 'lofi hiphop', 100, 3.8, 5, 5]

print('the last element of L1 is ',L1.pop())
print('the second to last element of L1 is ',L1.pop(-2))
print('the updated list ',L1)

the last element of L1 is  5
the second to last element of L1 is  3.8
the updated list  ['Meluha', 'cycle', 'wallet', 50, '4 litres', 'lofi hiphop', 100, 5]


append operation

In [199]:
L1 = ['Meluha', 'cycle', 'wallet', 50, '4 litres', 'lofi hiphop', 100, 3.8, 5, 5]
L1.append('toast')
print(L1)

['Meluha', 'cycle', 'wallet', 50, '4 litres', 'lofi hiphop', 100, 3.8, 5, 5, 'toast']


remove operation

In [93]:
print(L1)
L1.remove('Meluha')
print(L1)

['Meluha', 'cycle', 'wallet', 50, '4 litres', 'lofi hiphop', 100, 3.8, 5, 5, 'toast']
['cycle', 'wallet', 50, '4 litres', 'lofi hiphop', 100, 3.8, 5, 5, 'toast']


In [94]:
print(L1)
del L1[0:3]
print(L1)

['cycle', 'wallet', 50, '4 litres', 'lofi hiphop', 100, 3.8, 5, 5, 'toast']
['4 litres', 'lofi hiphop', 100, 3.8, 5, 5, 'toast']


add elements : one of the operation is append which is shown above although there are other ways too. 

In [103]:
L2 = ['power', 'greed', 'apathy', 'corruption', 'hope']
print(L2)
L2 = L2 + ['batman', 'joker']
print(L2)

L3 = ['scarecrow', 'riddler']
L2 = L2 + L3
print(L2)
L2.extend(['harley', 'cobblepot'])
print(L2)

['power', 'greed', 'apathy', 'corruption', 'hope']
['power', 'greed', 'apathy', 'corruption', 'hope', 'batman', 'joker']
['power', 'greed', 'apathy', 'corruption', 'hope', 'batman', 'joker', 'scarecrow', 'riddler']
['power', 'greed', 'apathy', 'corruption', 'hope', 'batman', 'joker', 'scarecrow', 'riddler', 'harley', 'cobblepot']


Sort

In [104]:
print(sorted(L2))

['apathy', 'batman', 'cobblepot', 'corruption', 'greed', 'harley', 'hope', 'joker', 'power', 'riddler', 'scarecrow']


In [105]:
L4 = [1, 33, 43, 2, 3, 44, 56, 56, 2, 3, 76, 56, 767]
print(sorted(L4))

[1, 2, 2, 3, 3, 33, 43, 44, 56, 56, 56, 76, 767]


In [108]:
L4.sort(reverse = True)
print(L4)

L4.sort(reverse = False)
print(L4)

[767, 76, 56, 56, 56, 44, 43, 33, 3, 3, 2, 2, 1]
[1, 2, 2, 3, 3, 33, 43, 44, 56, 56, 56, 76, 767]


# 6. Create a tuple and perform pop, append, update, remove, delete, add element and sort operation



In [141]:
T1 = ('Meluha', 'cycle', 'wallet', 50, '4 litres', 'lofi hiphop', 100, 3.8, 5, 5)
print(type(T1))

<class 'tuple'>


Since a tuple is immutable, the operations such as pop, append, remove, adding element or sort operation do not work. However the tuple can be copied in to list and all of the operations which modifies its content can work 

# 7. Create a set and perform pop, append, update, remove, delete, add element and sort operation

In [168]:
S1 = {'Meluha', 'cycle', 'wallet', 50, '4 litres', 'lofi hiphop', 100, 3.8, 5, 5}
print('The type of S1 is',type(S1))
print('The content of S1 is',S1)

The type of S1 is <class 'set'>
The content of S1 is {'lofi hiphop', 3.8, 100, 5, 'Meluha', 50, 'cycle', '4 litres', 'wallet'}


pop operation 

In [169]:
print(S1.pop())
print('The content of S1 is',S1)

lofi hiphop
The content of S1 is {3.8, 100, 5, 'Meluha', 50, 'cycle', '4 litres', 'wallet'}


Append operation do not work for set. However we can use 'add' and 'update' operation for a set 

In [170]:
S1.add('chowmein')
S1.update(['noodles','dimsum'])
print('The content of S1 is',S1)

The content of S1 is {'chowmein', 3.8, 100, 5, 'noodles', 'Meluha', 50, 'cycle', '4 litres', 'wallet', 'dimsum'}


In [171]:
S1.remove('chowmein')
print('The content of S1 is',S1)

The content of S1 is {3.8, 100, 5, 'noodles', 'Meluha', 50, 'cycle', '4 litres', 'wallet', 'dimsum'}


delete operation

In [172]:
S1.clear()
print(S1)

set()


Sort operation do not work if the set contain both str and int type elements. We make a set with int type values. 

In [181]:
S1 = {12, 213, 21, 32, 54, 65, 23, 87, 54, 45, 21, 0.9}
print(sorted(S1))

[0.9, 12, 21, 23, 32, 45, 54, 65, 87, 213]


# 8. Create a Dictionary and perform pop, append, update, remove, delete, add element and sort operation

In [213]:
D1 = {'Joydeep':(150, 200), 'Subhayan':200, 'Mrinal':200, 'Soumitra':500}
print('The type of D1 is',type(D1))

The type of D1 is <class 'dict'>


pop and append operation do not work with dictionries. 
However we can use 'update' operation to add a new element in a dictionary. 

In [214]:
print(D1.update({'subhjit':300}))
print(D1)

D1['subhajit'] = [50, 200, 250]#to update the values of a certain key
print(D1)

None
{'Joydeep': (150, 200), 'Subhayan': 200, 'Mrinal': 200, 'Soumitra': 500, 'subhjit': 300}
{'Joydeep': (150, 200), 'Subhayan': 200, 'Mrinal': 200, 'Soumitra': 500, 'subhjit': 300, 'subhajit': [50, 200, 250]}


remove operation do not work in dictionary however we can use 'del' and 'clear' that do work

In [215]:
del D1['Soumitra']
print('The up to date content of D1 is\n',D1)

The up to date content of D1 is
 {'Joydeep': (150, 200), 'Subhayan': 200, 'Mrinal': 200, 'subhjit': 300, 'subhajit': [50, 200, 250]}


Sort operation : this sort only sorts the Keys of the dictionary

In [225]:
print(sorted(D1))

{'Joydeep': (150, 200), 'Subhayan': 200, 'Mrinal': 200, 'subhjit': 300, 'subhajit': [50, 200, 250]}


# 9. How to make a copy of list, tuple and dictionary

In [228]:
#Copying list

L_fruits = ['coconut', 'mango', 'dates', 'figs', 'avocado']
L_fruits_new = L_fruits.copy()
print('The content of L_fruits',L_fruits)
print('The memory address of L_fruits is',id(L_fruits),'\n')

print('The content of address of L_fruits_new is',L_fruits_new)
print('The memory address of L_fruits_new is',id(L_fruits_new),'\n')

The content of L_fruits ['coconut', 'mango', 'dates', 'figs', 'avocado']
The memory address of L_fruits is 4584689488 

The content of address of L_fruits_new is ['coconut', 'mango', 'dates', 'figs', 'avocado']
The memory address of L_fruits_new is 4586765760 



A tuple cannot be copied as it is immutable. 

In [10]:
#Copying dictionary

L_DC_heros = {'bruce':['batman',100], 'clerk':['superman',79], 'diana':['wonderwoman',70], 'wally':['flash',75], 'john':['martian manhunter',68]}
L_DC_heros_new = L_DC_heros.copy()
print('The content of L_fruits',L_DC_heros)
print('The memory address of L_fruits is',id(L_DC_heros),'\n')

print('The content of address of L_fruits_new is',L_DC_heros_new)
print('The memory address of L_fruits_new is',id(L_DC_heros_new),'\n')

The content of L_fruits {'bruce': ['batman', 100], 'clerk': ['superman', 79], 'diana': ['wonderwoman', 70], 'wally': ['flash', 75], 'john': ['martian manhunter', 68]}
The memory address of L_fruits is 4338646704 

The content of address of L_fruits_new is {'bruce': ['batman', 100], 'clerk': ['superman', 79], 'diana': ['wonderwoman', 70], 'wally': ['flash', 75], 'john': ['martian manhunter', 68]}
The memory address of L_fruits_new is 4338692176 



# 10. Write a function which accept input from keyboard and check if student grade should be First division, second division or Fail 


In [12]:
grade = float(input('Enter the student\'s grade \n'))

first_div = 8.0
second_div = 6.0
passing = 4

if (grade >=first_div):
    print('The student has passed with first division')
elif (second_div <= grade < first_div):
    print('The student has passed with second division')
elif (passing <= grade < second_div):
    print('The student has passed')
else:
    print('The student has failed')

Enter the student's grade 
7.8
The student has passed with second division


# 11. 
# teamA = {'India', 'Australia','Pakistan', 'England'}
# teamB = {'Bangladesh', 'New Zealand', 'West Indies', 'India'}

# 12. use add, clear, copy, difference, differenc_update(), discard, intersection, intersection_update, 

# 13. remove, symmetric_difference,  union, update

In [13]:
teamA = {'India', 'Australia', 'Pakistan', 'England'}
teamB = {'Bangladesh', 'New Zealand', 'West Indies', 'India'}

add operation

In [14]:
teamA.add('USA')
print(teamA)


{'Pakistan', 'USA', 'England', 'India', 'Australia'}


In [15]:
teamB_copy = teamB.copy()
print(teamB)

{'New Zealand', 'West Indies', 'Bangladesh', 'India'}


difference operation

In [16]:
print(teamA.difference(teamB))

{'England', 'Australia', 'Pakistan', 'USA'}


difference_update operation

In [17]:
teamA.difference_update(teamB)
print(teamA)

{'Pakistan', 'USA', 'England', 'Australia'}


discard operation

In [18]:
teamA = {'India', 'Australia', 'Pakistan', 'England'}
teamA.discard('India')
print(teamA)

{'Pakistan', 'Australia', 'England'}


intersection operation

In [19]:
teamA = {'India', 'Australia', 'Pakistan', 'England'}
teamB = {'Bangladesh', 'New Zealand', 'West Indies', 'India'}

print(teamA.intersection(teamB))

{'India'}


intersection_update operation

In [20]:
teamA = {'India', 'Australia', 'Pakistan', 'England'}
teamB = {'Bangladesh', 'New Zealand', 'West Indies', 'India'}

teamA.intersection_update(teamB)
print(teamA)

{'India'}


remove operation

In [21]:
teamA = {'India', 'Australia', 'Pakistan', 'England'}
teamB = {'Bangladesh', 'New Zealand', 'West Indies', 'India'}

teamA.remove('India')
print(teamA)

{'Pakistan', 'Australia', 'England'}


symmetric differnce operation

In [22]:
teamA = {'India', 'Australia', 'Pakistan', 'England'}
teamB = {'Bangladesh', 'New Zealand', 'West Indies', 'India'}

print(teamA.symmetric_difference(teamB))
print(teamB.symmetric_difference(teamA)) #obviously they are equal

{'Pakistan', 'England', 'West Indies', 'Bangladesh', 'Australia', 'New Zealand'}
{'Pakistan', 'England', 'West Indies', 'Bangladesh', 'Australia', 'New Zealand'}


# 14. What is list comprehension explain with 2 examples

In general list comprehensions imply an creating list object using iterable variables using loops or conditional elements or both. This is helpful as in this way lists having large number of elements can be analysed. 

First example : 

In [23]:
teamA = ['India', 'Australia', 'Pakistan', 'England']
new_team = [team for team in teamA if team != 'Australia']
print(new_team)

['India', 'Pakistan', 'England']


In the above example we made a new list from 'teamA' using a 'for' loop to go through the elements of 'teamA' and we created a 'new_team' consisting of elements other than one inside the if clause. 

Second example :

In [24]:

number_1 = [float(x) for x in range(1,50) if ((x%2 == 0) and (x%3 == 0))]
number_2 = [float(x) for x in range(1,50) if ((x%5 == 0) and (x%3 == 0))]

number_3 = [float(x/y) for x in number_1 for y in number_2]
print('number_1 :',number_1)
print('number_2 :',number_2)
print('number_3 :',number_3)

number_1 : [6.0, 12.0, 18.0, 24.0, 30.0, 36.0, 42.0, 48.0]
number_2 : [15.0, 30.0, 45.0]
number_3 : [0.4, 0.2, 0.13333333333333333, 0.8, 0.4, 0.26666666666666666, 1.2, 0.6, 0.4, 1.6, 0.8, 0.5333333333333333, 2.0, 1.0, 0.6666666666666666, 2.4, 1.2, 0.8, 2.8, 1.4, 0.9333333333333333, 3.2, 1.6, 1.0666666666666667]


In the above example we created two lists via list comprehension technique. The list 'number_1' contain all
the integer numbers between 1 and 50 that are both divisible by 2 and 3. Similarly the 'number_2' contain 
all the ineger numbers in the same range that are both divisible by 5 and 3. We then created an another list
'number_3' where each element of 'number_1' is divided by elements of 'number_2'

# 15. What is the difference between a list and a tuple, explain with example

We note that both, lists and tuples are collections of unordered elements (Eg. stings, integers, floats, even lists or tuples, etc.). Both of them can contain elements that are identical. However there is key differences between them. The elements of a list are changeble while the content of the tuple are not changle. We show this via a simple example in below. 

In [25]:
A_list = ['ironman', 'hulk', 'antman', 1, 2, 2, 55.6, ['scarlet witch', 'vision'], ['thor', 'stormbreaker']]
A_tuple = ('ironman', 'hulk', 'antman', 1, 2, 2, 55.6, ['scarlet witch', 'vision'], ['thor', 'stormbreaker'])

print(A_list)
print(A_tuple)

A_list.append(['skynet'])
print(A_list)

A_tuple.append(['skynet'])
print(A_tuple)

['ironman', 'hulk', 'antman', 1, 2, 2, 55.6, ['scarlet witch', 'vision'], ['thor', 'stormbreaker']]
('ironman', 'hulk', 'antman', 1, 2, 2, 55.6, ['scarlet witch', 'vision'], ['thor', 'stormbreaker'])
['ironman', 'hulk', 'antman', 1, 2, 2, 55.6, ['scarlet witch', 'vision'], ['thor', 'stormbreaker'], ['skynet']]


AttributeError: 'tuple' object has no attribute 'append'

As we can observe above python show error while trying to add 'skynet' in 'A_tuple'

# 16. What is the output of :

if 1 and 0:

   print("Sucess 1 and 0")

elif 0 and 0:

   print("Sucess 0 and 0")

elif 0 and 1 or 1:

   print("Sucess 0 and 1 or 1")

elif 0 and 0 or 1 and 1:

   print("Sucess : 0 and 0 or 1 and 1")
   
ANS : In the first 'if' condition '1 and 0' results in 0. Therefore the control of code goes to the next 
'elif' condition. Here since the output of '0 and 0' is 0, the control goes to the next 'elif' condition.
Here the output of '0 and 1 or 1' is 1 as '0 and 1' results in 0 and '0 or 1' is 1. Therefore the output of the above code is 'Success 0 and 1 or 1'. We run the above code below to verify it.

In [7]:
if 1 and 0:
    print("Sucess 1 and 0")
elif 0 and 0:
    print("Sucess 0 and 0")
elif 0 and 1 or 1:
    print("Sucess 0 and 1 or 1")
elif 0 and 0 or 1 and 1:
    print("Sucess : 0 and 0 or 1 and 1")


Sucess 0 and 1 or 1


# 17. What is the output of the following code.

list_of_lists = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]

for list1 in list_of_lists: 

    for x in list1: 
    
        print(x)
    
    print(list1)

ANS : In the first 'for' loop, the variable 'list1' each of the lists in the 'list_of_lists', then the in next
'for' loop the variable 'x' goes through the content of list in the variable 'list1'. In the next step the content of 'x' is printed which is the content of the list in 'list1'. After the execution of second 'for' loop the content of 'list1' is printed. Then the first 'for' loop runs for the second list in the 'list_of_lists' till the last list. This verified from the output of the code. 


In [11]:
list_of_lists = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]

for list1 in list_of_lists: 
    for x in list1: 
        print(x)
    print(list1)




10
20
30
[10, 20, 30]
40
50
60
[40, 50, 60]
70
80
90
[70, 80, 90]


# 18. print  the numpy version and the configuration

In [45]:
import numpy as np
print('The version of numpy is : ',np.version.version)
print('The configuration of numpy is : ',np.show_config())

The version of numpy is :  1.17.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
The configuration of numpy is :  None


# 19. Create a vector with values ranging from 10 to 29

In [46]:
Vector = np.arange(10, 30, 1)
print(Vector)
print(type(Vector))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
<class 'numpy.ndarray'>


# 20. Create a 3x3 matrix with values ranging from 0 to 8 

In [51]:
matrix = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(matrix)
print(matrix.ndim)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
2


# 21. Create a 10x10 array with random values and find the minimum and maximum values

In [62]:
Random = np.random.random((10, 10))
print(Random,'\n')
print('The shape of the matrix is :',Random.shape)

[[0.76319507 0.84247502 0.59284143 0.0740451  0.82367462 0.50143417
  0.18767802 0.67988504 0.8558072  0.90313514]
 [0.7744469  0.41369141 0.66837499 0.20062953 0.03243708 0.75561596
  0.20965637 0.25167261 0.32154383 0.94180905]
 [0.05729208 0.40535826 0.55403649 0.96924076 0.53565802 0.82717682
  0.28149794 0.68234199 0.62178347 0.09141002]
 [0.6986701  0.87816932 0.61922583 0.1962197  0.77675506 0.27816812
  0.94130097 0.41172047 0.61272174 0.65529948]
 [0.91764585 0.44446464 0.43157421 0.10105822 0.22949388 0.18948248
  0.47410015 0.40150888 0.96722662 0.47593873]
 [0.65501046 0.83572741 0.16990253 0.26786762 0.00825486 0.17330531
  0.93225557 0.74003118 0.35117399 0.1773351 ]
 [0.14267898 0.76434261 0.81638505 0.02795705 0.72580516 0.06587277
  0.39692878 0.28451275 0.93930528 0.35997853]
 [0.496919   0.8363649  0.14322123 0.30779106 0.03655843 0.80726099
  0.49979033 0.41088122 0.36832851 0.53802787]
 [0.53245611 0.77490075 0.55213509 0.94418498 0.94998311 0.76675022
  0.30955244

Maximum value

In [58]:
print(Random.max())

0.9937506972574608


Minimum value

In [59]:
print(Random.min())

0.009345055011570014


# 22. Create a random vector of size 30 and find the mean and median value value

In [72]:
Rand_vec = np.random.random((1, 30))
print(Rand_vec,'\n')

[[0.28122332 0.48778657 0.66520084 0.52175626 0.72641971 0.39926442
  0.67051309 0.1306334  0.55895332 0.29517887 0.63580058 0.240843
  0.29820756 0.12100451 0.35043703 0.67246261 0.17887785 0.39429153
  0.66147943 0.5993021  0.48784355 0.2609841  0.41489042 0.92775995
  0.92948454 0.49195228 0.62077398 0.03465374 0.17192127 0.15131485]] 



Mean

In [73]:
print(np.mean(Rand_vec))

0.4460404893849553


Median

In [74]:
print(np.median(Rand_vec))

0.4513384961655064


# 23. Define an array and mind the max value and index of max value

In [89]:
Array_1 = np.array([1, 2, 32, 43, 54, 21, 43, 35, 21, 32, 32, 3])

Maximum value

In [90]:
print(Array_1.max())

54


Index of the maximum value 

In [91]:
print(Array_1.argmax())

4


In [92]:
print(Array_1.__len__())

12


# 24. How to find the memory size of any array

The 'nbytes' command is an easy way to do this. The output of this command provides us with the total 
bytes required to store the array in the memory.

In [101]:
Array_2 = np.random.random((1, 20))
print(Array_2,'\n')
print('The memory size to store \'Array_2\' is',Array_2.nbytes,'bytes')

[[0.49118327 0.65098903 0.88760831 0.44751966 0.94656483 0.91407039
  0.56535973 0.30909898 0.80230258 0.79989882 0.95277274 0.86095545
  0.08961514 0.2433522  0.82455214 0.92394652 0.81251521 0.06285106
  0.22130416 0.91995745]] 

The memory size to store 'Array_2' is 160 bytes


# 25. Create a 3x3 identity matrix

In [102]:
Identity = np.eye(3)
print(Identity)              


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
